### ISSUE TITLE
Not picking up tap events

### ISSUE THREAD

**Issue by jamieisboss** [metafizzy/tap-listener#3]
Called plumber, he recommended this package so i ran:

```
npm init
```

then 

```
npm install tap-listener -save
```

on my bath and my bathroom sink to be sure.

Plumber said the package did not report any events except the taps turning on once in the night (I'd had a few beers that evening), still cannot find a drip but i swear i can hear one, can only be a bug in your software.

Please fix

**Comment by desandro** [comment]
😊
